# Generated by Django 5.1.7 on 2026-04-28 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_20260420_0827'),
        ('core', '0038_tenant_phase_log'),
    ]

    operations = [
    ]
